### ISSUE TITLE
New modules fail to start at launch

### ISSUE THREAD

**Issue by Terrance** [ActivityWatch/aw-qt#105]
I've just installed the 0.13.1 AppImage release, which includes aw-sync but does not enable it by default.

aw-qt's config updated to load it:

```toml
[aw-qt]
autostart_modules = ["aw-server", "aw-sync", "aw-watcher-afk", "aw-watcher-window"]
```

But when starting aw-qt I get the following:

![Screenshot_20240701_231109](https://github.com/ActivityWatch/aw-qt/assets/4025899/2a624905-5566-466a-8575-b458b7bc6414)

```
[2024-07-01 23:10:16][INFO][aw_sync]: Starting daemon...
[2024-07-01 23:10:16][INFO][aw_sync]: Pulling from all hosts
[2024-07-01 23:10:16][INFO][aw_sync::util]: Found remotes: ["hostname"]
```

The log ends there.  Pressing _Restart_ seems to result in the module loading successfully.  Enabling the module from the tray icon menu without updating `autostart_modules` also seems to start it without any problems.

The same happens trying to load aw-watcher-input, which also isn't enabled by default.

**Comment by galvanized** [comment]
Having the same issue. Manually enabled aw-sync in aw-qt config, get warning popup, no logs (or even a log directory). On Windows 10, 0.13.1 installed via installer. 
However, I've also had issues starting it from the tray menu.

**Comment by ErikBjare** [comment]
Try running aw-sync directly from a terminal and see what the output is.

**Comment by Terrance** [comment]
Having just attempted to start it early on boot, I got the following:

```
$ aw-sync
[2024-08-29 13:00:52][INFO][aw_sync]: Starting daemon...
[2024-08-29 13:00:52][INFO][aw_sync]: Pulling from all hosts
[2024-08-29 13:00:52][INFO][aw_sync::util]: Found remotes: ["hostname"]
Error: "Local server http://127.0.0.1:5600/ not running"
```

Note that the output ends at the same point, but trailed by what appears to be an error not via the logging framework to say the core service isn't running.  Probably these new modules depend on the core being up at their startup, but it's not ready yet?  It would also be useful to have that error captured by aw-qt.

**Comment by Terrance** [comment]
This is still happening in 0.13.2 -- any updates?

**Comment by ErikBjare** [comment]
Ah, looks like a race condition where the new modules are assuming the server to already be running and not waiting for it to start. 

I've started seeing the same on my system, will fix.

**Comment by ErikBjare** [comment]
Implemented `client.wait_for_start()` with exponential backoff instead of relying on heuristics like `sleep(1)`:
 - https://github.com/ActivityWatch/aw-client/pull/87
 - https://github.com/ActivityWatch/aw-server-rust/pull/495

Now used in aw-sync, and all watchers + aw-notify:
 - https://github.com/ActivityWatch/aw-watcher-afk/commit/9f9a4fd3c51635ba362a51ac8e7bc47abd56fa05
 - https://github.com/ActivityWatch/aw-watcher-window/commit/c80aa5adbbe5959fcb661148aeb9f3898e6b68f3
 - https://github.com/ActivityWatch/aw-watcher-input/commit/9bb5045456524b215ae11f422b80ec728c93bac7
 - https://github.com/ActivityWatch/aw-notify/commit/c5f31068a470e65c23399f7e60995bcf453c0bc8

Thanks for reporting!

**Comment by Terrance** [comment]
As far as I can tell, this hasn't made it into a release yet (the last one being from 5th October, just before the fix) -- is a new desktop release due soon?
