### ISSUE TITLE
When aw-qt crashes, aw-watcher-afk does not shut down

### ISSUE THREAD

**Issue by johan-bjareholt** [ActivityWatch/aw-qt#19]
Really odd behavior.
Reproducible by starting aw-qt and then doing "kill -9" on the aw-qt process.

**Comment by ErikBjare** [comment]
Yeah, I tried using a process group for this but I'm not that familiar with that part of POSIX.

Do you think you could look into that @johan-bjareholt?

**Comment by ErikBjare** [comment]
It seems that `kill -9` doesn't kill the whole group/session. You'd have to do `kill -9 -$PGID`.

A solution to prevent double-running processes would be to run a process check upon start and see if any `aw-*` processes are already running.

**Comment by johan-bjareholt** [comment]
> A solution to prevent double-running processes would be to run a process check upon start and see if any aw-* processes (that aw-qt wants to manage) are already running.

Here's a proposal for this

https://github.com/ActivityWatch/aw-client/pull/21

**Comment by ErikBjare** [comment]
Closing this since it only happens in the case of `kill -9`, which we can't do anything about.

**Comment by johan-bjareholt** [comment]
No, it does not only happen for `kill -9`, i only used kill when i tried to reproduce. Another way to reproduce on my machine is to simply press "open log folder", but in that case all modules continue running (aw-server, aw-watcher-afk and aw-watcher-window).

**Comment by ErikBjare** [comment]
Oh, fair enough. 

I think this depends on how Python crashes, if Python crashes with an internal error (possible that PyQt triggers this) instead of a normal Exception-caused crash then I'm not sure we can do much about it. If it crashes "normally" then I think the `atexit` should work (which I added [here](https://github.com/ActivityWatch/aw-qt/pull/21)).

**Comment by nikanar** [comment]
Once `aw-qt` dies, the other `aw-*` become [*orphan processes*](https://en.wikipedia.org/wiki/Orphan_process), and their `PPID` becomes 1 (for the init process, rather than having the value of their parent's `PID` (which in our case is also their `PGID`). Since [there is no formal tie between a child process and its parent](https://stackoverflow.com/questions/269494/how-can-i-cause-a-child-process-to-exit-when-the-parent-does)), it is normal, if undesirable, than children processes stay alive after the parent crashes. Children that would rather die than stay as orphans [typically poll their parents for aliveness](https://stackoverflow.com/a/2035683/1449460), for instance checking whether their own `PPID` ever becomes 1 (and then shutting down).

<details>
<summary>This can be done in this way in Python.</summary>

```
# inspired from http://www.programcreek.com/python/example/4464/os.getppid
while True: # watcher loop, run() or heatbeat_loop()
    if os.getppid() == 1:
        sys.exit()
```
This kills the watchers when `aw-qt` is `kill -9`-ed.

Then I've been looking for the proper way to terminate the watchers, and while `aw-qt.Module.stop` looked nice, I couldn't access it, so I elected to just `break` out of the main loops. If there's a better thing to do, please let me know as I didn't find one.

PR will come in as soon as I figure a proper git way out of my local mess (I've been adding `--user` to all Makefiles here, and ``). 
</details>


<details>
<summary>Some other solution using prctl</summary>

[Another solution](https://stackoverflow.com/questions/284325/how-to-make-child-process-die-after-parent-exits) involves **prctl** : `prctl(PR_SET_PDEATHSIG, SIGTERM);`, but that seems [easier in C than in Python](https://stackoverflow.com/questions/38609686/terminate-a-forked-process-in-python-when-the-parent-process-dies-using-prctl).  

[**python-prctl** is a thing](https://github.com/seveas/python-prctl), if someone wants to go that way.
</details>

<details> 
<summary>And this track was yet another option but led nowhere</summary>

Otherwise, per section 10.6.4 in [this document](http://www.informit.com/articles/article.aspx?p=397655&seqNum=6), supposedly all *orphaned process groups* receive a **`SIGHUP`**, and could take that hint to die graciously (**but it doesn't seem to apply here**, maybe because [reasons](https://stackoverflow.com/questions/19756633/why-sighup-signal-not-received-when-becoming-an-orphaned-process-group?rq=1) ; [this question](https://stackoverflow.com/questions/39103871/daemonization-and-sighup) is super relevant but gets complicated). [That would take](https://stackoverflow.com/questions/21929690/what-are-the-consequences-of-killing-a-python-script-with-sighup) to [install a SIGHUP handler](https://docs.python.org/3/library/signal.html). That would have simply entailed adding `signal.signal(signal.SIGHUP, signal.SIGTERM)` inside `heartbeat_loop` in `aw-watcher-window/main.py`.
</details>

**Comment by johan-bjareholt** [comment]
@nikanar Awesome! Much better solution than my suggestion.

Out of the 3 solutions you found the one you selected was clearly most clean.

Will also work nicely even if not run with aw-qt.

Will check the PRs and merge :)

Thanks for the help!

**Comment by ErikBjare** [comment]
Amazing work, learned a lot from reading those links. 

But, as I mentioned in comments on the PRs, there might be an issue with the taken approach when run using the PyInstaller binaries. I'm confident we can find a way around that however.

**Comment by ErikBjare** [comment]
Continued discussions should probably go here. 

So, @nikanar did a nice fix with the PPID detection but I don't think that'll work with PyInstaller due to it using a bootloader process that in turn starts the application process. 

Details here: https://pythonhosted.org/PyInstaller/advanced-topics.html#the-bootstrap-process-in-detail

The process tree would look something like this when run using the PyInstaller (iirc):

 - aw-qt (bootloader) 
   - aw-qt
      - aw-server (bootloader) 
         - aw-server
      - aw-watcher-afk (bootloader) 
         - aw-watcher-afk
      - ...

**Comment by nikanar** [comment]
If that's right, then when running under PyInstaller, the children should look for the PPID of their parent process (the PyInterpreter) to see if *that* is 1 because aw-qt died. But then, I also have no idea if `PPID`s work the same under Windows either.
