### ISSUE TITLE
error loading python dll python35.dll (error code 1114)

### ISSUE THREAD

**Issue by Kewings** [ActivityWatch/aw-qt#23]
i download windows version "activitywatch-windows-x86_64-v0.7.0b1.zip" from https://github.com/ActivityWatch/activitywatch/releases.

unzip and run aw-qt follow the guide, but it reported error messages like above.
![image](https://user-images.githubusercontent.com/29881381/28812639-31244bb4-76c8-11e7-8d42-09eb38460c33.png)

before aw unziped, i had already installed python 3.6.2 in my computer. 
so, how can i resolve it?

Many thanks.

**Comment by johan-bjareholt** [comment]
First off, you do not need to install python for the activitywatch EXEs to work, since python is bundled with the program.

The issue itself however seems to be related to PyInstaller. According to [this github issue](https://github.com/pyinstaller/pyinstaller/issues/2542) it might be specific to Windows 7. For me it works on Windows 10, so I would like to try this in a virtual machine with windows 7. I am on holiday currently though for a couple of more weeks so I will not have time to test this anytime soon unfortunately.

You could also try and run it as an administrator (right click in the file, properties, and then check the box "run as administrator"), but that's not a permanent solution since it's a security risk.

**Comment by ErikBjare** [comment]
@Kewings Are you using a 32bit version of Windows 7?

**Comment by Kewings** [comment]
hi all,
Thanks for your quick response.
I used windows7 64bit.
And i also tried as administrator in file's properties and  command as administrator.
I installed python before for another projects.

I also mind it might be related to windows system, so i tried the project in ubuntu this afternoon. Only server finished till now.
So i think the windows' issue can be tried later.
Thanks.

**Comment by ErikBjare** [comment]
@Kewings Alright. Thanks a lot for filing the issue. We'd never have tested it ourselves.

If you really need ActivityWatch on your Windows 7 machine, you may try and build it yourself, but be warned: it's a bit messy on Windows systems. But here's the Appveyor config we're using: https://github.com/ActivityWatch/activitywatch/blob/master/.appveyor.yml

I've made an issue about this in the main repo for increased exposure.

**Comment by ErikBjare** [comment]
Closing due to age. Windows 7 will likely never get support.
