### ISSUE TITLE
Option to not open Command Prompt window on start.

### ISSUE THREAD

**Issue by ethanhs** [ActivityWatch/aw-qt#30]
I just started using AW and I ran aw-qt.exe. To my surprise it opened a logging window, which I am sure is nice for debugging, but I'd like an option to turn it off. Thank you for this program!

**Comment by ErikBjare** [comment]
Thanks for creating an issue!

You're right. I don't think we can make it an option but now showing it should definitely be the default. It's something that can be easily fixed by a minor modification to the build process (you can see the line we need to change here: https://github.com/ActivityWatch/aw-qt/blob/master/aw-qt.spec#L48) so I'll get around to doing that.

**Comment by johan-bjareholt** [comment]
I mentioned this to you a couple of weeks ago aswell @ErikBjare, I guess we both forgot to do anything about it.
It looks incredibly ugly and the logs are available anyway, so I removed it now in df609bb.
In my opinion that is almost worth doing a point release for in my opinion, it is quite annoying and makes you want to use it on a day-to-day basis on Windows.

**Comment by ethanhs** [comment]
It seems this was reverted in https://github.com/ActivityWatch/aw-qt/commit/c1f4a5ddf5fb573fcf51ae0a68138e1520365c92

**Comment by ErikBjare** [comment]
Yeah, that change might have unintended consequences on other platforms. The PR here describes the issue and proposes a fix: https://github.com/ActivityWatch/aw-qt/pull/31

**Comment by ErikBjare** [comment]
Has been fixed and released a while back, closing.
