### ISSUE TITLE
Building with newest pyqt fails

### ISSUE THREAD

**Issue by chozabu** [ActivityWatch/aw-qt#37]
After following official build info

(venv) chozabu@chozabu-32:~/devel/activitywatch$ pip freeze
...
PyQt5==5.11.2
...

versions: 5.6, 5.7, 5.7.1, 5.8, 5.8.1.1, 5.8.2, 5.9, 5.9.1, 5.9.2, 5.10, 5.10.1, 5.11.2)

(venv) chozabu@chozabu-32:~/devel/activitywatch$ pip install PyQT5==5.10.1

[build now works]

**Comment by ErikBjare** [comment]
PyQt5<5.10 is specified in setup.py:

https://github.com/ActivityWatch/aw-qt/blob/f155d0e2c4675785376246331a8875e1ac3ef38d/setup.py#L14

However you still get this because you probably used the submodule version in the main activitywatch repo. I'll update the main package to use the now working version.

**Comment by ErikBjare** [comment]
Fixed in https://github.com/ActivityWatch/activitywatch/commit/616b92e7101137f379ccfcd8aab2d62dc2f676d8

**Comment by chozabu** [comment]
Glad it is fixed - I was just following the given build instructions.

**Comment by ErikBjare** [comment]
@chozabu Got that, sorry for the trouble :smile:

**Comment by chozabu** [comment]
@ErikBjare no trouble, thanks for the fix ;)
