### ISSUE TITLE
Cannot start on macOS Catalina

### ISSUE THREAD

**Issue by MrDarkSkil** [ActivityWatch/aw-qt#50]
When i want to run aw-qt, macOS stop the app and if we force macOS to launch aw-qt in settings the same message appears for another python library and so on it does not end any more.

<img width="687" alt="Capture d’écran 2019-11-26 à 22 11 01" src="https://user-images.githubusercontent.com/13404544/69673455-a3f56d80-109a-11ea-853c-a344dcef91e4.png">

Spec infos:
- MacOS 10.15

If you need more details tell me :)

**Comment by ErikBjare** [comment]
Has also been reported here: https://forum.activitywatch.net/t/catalina-launchagent-fail/385

It seems the right way is to code sign the releases, but that costs money.

**Comment by pqrth** [comment]
@ErikBjare, thanks a ton for developing ActivityWatch and looking into this issue.

> It seems the right way is to code sign the releases, but that costs money.

Now, code signing is not a issue for now because it can be circumvented: [macOS user doc](https://support.apple.com/en-in/HT202491).

> Before that we might even have to package it as an app.

This is actually causing a user experience issue, where [macOS's Gatekeeper](https://en.wikipedia.org/wiki/Gatekeeper_(macOS)) bombards users with a ton of security pop-ups asking to allow all the unsigned binaries when a fresh version of `aw-qt` is first opened. Usually, when software is packaged as an unsigned app, like [laurent22/joplin](https://github.com/laurent22/joplin), then there are only 2 pop ups and 3 clicks.

Now, ActivityWatch's `aw-qt` unsigned binary seems to run following unsigned binaries:
1. `aw-server`
1. `aw-watcher-afk`

Moreover, all these 3 unsigned binaries further use following unsigned binaries:
1. `Python`
1. `libssl.1.1.dylib`
1. `libcrypto.1.1.dylib`
1. `_speedups.cpython-37m-darwin.so`
1. `_asyncio.cpython-37m-darwin.so`
1. `libsqlite3.0.dylib`
1. `pvectorc.cpython-37m-darwin.so`

Simultaneously, `aw-qt` also shows a few pop-ups informing that `aw-server` or `aw-watcher-afk` failed to start, so one need to restart that as well.

So, that is at least 3 * 7 = **21 unsigned binaries**. 2 pop ups and 4 clicks for each binaries totals to minimum **84 clicks**. I've mindlessly allowed all the `aw-qt` unsigned binaries and it's working fine, but I'll have to do it again when I want to upgrade to a newer version.

> Is our brew recipe also not working? Could you test?

The [brew formulae](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/activitywatch.rb) is installing the software as expected.

---

After I drafted this message, I found out that macOS app is in works: [ActivityWatch/activitywatch#334](https://github.com/ActivityWatch/activitywatch/issues/334#issuecomment-593076612) 😅

**Comment by xylix** [comment]
There is a self-signed release now at https://github.com/ActivityWatch/activitywatch/releases/tag/v0.9.0 which closes this problem.
